### ISSUE TITLE
Apple M2 Silicon Error: Input type (MPSFloatType) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by murtuk** [volotat/SD-CN-Animation#131]
Hello, I am using an Apple Silicon Mac with 32 GB RAM. Trying vid2vid transformation. 

First I had an error "RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU."

Later, I tried methods from other posts and tried them one by one and together: 
1st method: "look for this File "/stable-diffusion-webui/extensions/sd-cn-animation/scripts/core/txt2vid.py",
@ line 51,in **FloweR_load_model FloweR_model.load_state_dict(torch.load(model_path))**change that to > FloweR_model.load_state_dict(torch.load(model_path, map_location="cpu"))"

2nd method: "in flow_utils.py change "RAFT_model.load_state_dict(torch.load(args.model))" to "RAFT_model.load_state_dict(torch.load(args.model, map_location=device))"."

After the changes, I can see having the first frame of the video changed succesfully. But then give me this error and stop generating further frames: "An exception occurred while trying to process the frame: Input type (MPSFloatType) and weight type (torch.FloatTensor) should be the same"

As I searched the internet, I found that error is happening because something like the model and data is in different places (like CPU or GPU).

So, any help appreciated how to fix that.
Thanks.

**Comment by pupubear007** [comment]
"look for this File "/stable-diffusion-webui/extensions/sd-cn-animation/scripts/core/vid2vid.py", @ line 141 **if sdcn_anim_tmp.process_counter % prepare_steps == 0 and not sdcn_anim_tmp.frames_prepared: # prepare next 10 frames for processing
        #clear_memory_from_sd()**

add **device = torch.device("cpu")** @ line 142
Hope this works for you

**Comment by murtuk** [comment]
now got "An exception occurred while trying to process the frame: name 'torch' is not defined" so I added "import torch" on top. And now it works, thank you very much.

**Comment by melbouhy** [comment]
> "look for this File "/stable-diffusion-webui/extensions/sd-cn-animation/scripts/core/vid2vid.py", @ line 141 **if sdcn_anim_tmp.process_counter % prepare_steps == 0 and not sdcn_anim_tmp.frames_prepared: # prepare next 10 frames for processing #clear_memory_from_sd()**
> 
> add **device = torch.device("cpu")** @ line 142 Hope this works for you

still having the same error 
`stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 136, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.` 
any idea why?

**Comment by kznrluk** [comment]
In my M1 MacBook Pro, I had to make modifications in vid2vid.py and flow_utils.py, one place each.

First, in vid2vid.py, please change the part where you input device = torch.device("cpu") to device = 'mps'. In my environment, the import torch at the beginning was unnecessary.

```
if sdcn_anim_tmp.process_counter % prepare_steps == 0 and not sdcn_anim_tmp.frames_prepared: # prepare next 10 frames for processing
        #clear_memory_from_sd()
 -       device = devices.get_optimal_device()
 +      device = 'mps' // here
```

Next, in flow_utils.py which is in the same folder, add the following line around line 55:

```
-    RAFT_model.load_state_dict(torch.load(args.model))
+    RAFT_model.load_state_dict(torch.load(args.model, map_location=torch.device(device)))
```

With these changes, it started working in my environment.

**Comment by frankRenlf** [comment]
you need to set: net.to(devices)
then it will be ok
